application: sonorous-lyceum-717
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*)
  static_files: \1
  upload: (.*)

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest