application: sonorous-lyceum-717
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /index
  static_files: static/index.html
  upload: static/index.html