application: sonorous-lyceum-717 
version: 1  
runtime: python27  
api_version: 1

default_expiration: "1d"  
threadsafe: yes

handlers:
- url: /(.*)/
  static_files: \1/index.html
  upload: .*/index.html

- url: /.*
  static_dir: static