application: sonorous-lyceum-717
version: 1
runtime: python
api_version: 1

handlers:
handlers:
- url: /(.+)/
  static_files: static/\1/index.html
  upload: static/HTML/(.+)/index.html

# site root
- url: /
  static_files: static/index.html
  upload: static/HTML/index.html

# Redirect Everything else
- url: /(.+)
  static_files: static/\1
  upload: static/HTML/(.+)