application: sonorous-lyceum-717
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  upload: index.html
  static_files: index.html
  
- url: /img
  static_dir: static_files/img
  
- url: /bootstrap
  static_dir: static_files/bootstrap

- url: /assets
  static_dir: static_files/assets
