application: sonorous-lyceum-717 
version: 1  
runtime: python27  
api_version: 1

default_expiration: "1d"  
threadsafe: yes

handlers:  
# index files
- url: /(.+)/
  static_files: index.html
  upload: index.html
  expiration: "15m"

- url: /(.+)
  static_files: index.html
  upload: index.html
  expiration: "15m"

# site root
- url: /
  static_files: index.html
  upload: index.html
  expiration: "15m"